<?xml version="1.0" standalone="yes"?>
<!--
Copyright (C) 1991-2012 Altera Corporation
Your use of Altera Corporation's design tools, logic functions 
and other software and tools, and its AMPP partner logic 
functions, and any output files from any of the foregoing 
(including device programming or simulation files), and any 
associated documentation or information are expressly subject 
to the terms and conditions of the Altera Program License 
Subscription Agreement, Altera MegaCore Function License 
Agreement, or other applicable license agreement, including, 
without limitation, that your use is for the sole purpose of 
programming logic devices manufactured by Altera and sold by 
Altera or its authorized distributors.  Please refer to the 
applicable agreement for further details.

Symbol generated by Quartus II 64-Bit
Version 12.1 Build 243 01/31/2013 Service Pack 1 SJ Web Edition
on 08/12/2013 15:19:09
-->
<!DOCTYPE PART_RECORD [<!ELEMENT PART_RECORD (MFRS|PARAMETERS|PINOUT_LABELS|DATA_SHEET)*>
<!ATTLIST PART_RECORD PART_NUMBER CDATA #IMPLIED>
<!ATTLIST PART_RECORD PART_DESCRIPT CDATA #IMPLIED>
<!ELEMENT MFRS (MFR)*>
<!ELEMENT MFR EMPTY>
<!ATTLIST MFR NAME CDATA #IMPLIED>
<!ATTLIST MFR STATUS CDATA #IMPLIED>
<!ELEMENT PARAMETERS (PARAMETER)*>
<!ELEMENT PARAMETER EMPTY>
<!ATTLIST PARAMETER NAME CDATA #IMPLIED>
<!ATTLIST PARAMETER VALUE CDATA #IMPLIED>
<!ELEMENT PINOUT_LABELS (PIN*)>
<!ATTLIST PINOUT_LABELS TYPE CDATA #IMPLIED>
<!ELEMENT PIN EMPTY>
<!ATTLIST PIN PIN_NUM CDATA #IMPLIED>
<!ATTLIST PIN FUNCTION CDATA #IMPLIED>
<!ATTLIST PIN SIGNAL CDATA #IMPLIED>
<!ATTLIST PIN IO CDATA #IMPLIED>
<!ATTLIST PIN CONTROL CDATA #IMPLIED>
<!ATTLIST PIN POLARITY CDATA #IMPLIED>
<!ELEMENT DATA_SHEET (IMAGE)*>
<!ELEMENT IMAGE EMPTY>
<!ATTLIST IMAGE IMAGE_DATE CDATA #IMPLIED>
<!ATTLIST IMAGE MFR_NAME CDATA #IMPLIED>
<!ATTLIST IMAGE xml:LINK CDATA #IMPLIED>
<!ATTLIST IMAGE ACTUATE CDATA #IMPLIED>
<!ATTLIST IMAGE HREF CDATA #IMPLIED> ]>
<PART_RECORD PART_NUMBER="EP2C50F484C6" PART_DESCRIPT="Programmable Logic Device (PLD)">
<MFRS>
<MFR NAME="Altera Corp" STATUS="Preliminary"/>
</MFRS>
<PARAMETERS>
<PARAMETER NAME="Technology" VALUE="CMOS"/>
<PARAMETER NAME="Family Name" VALUE="Cyclone II"/>
</PARAMETERS>
<PINOUT_LABELS TYPE="EXTENDED">
<PIN PIN_NUM="F5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C4" FUNCTION="~ASDO~" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C3" FUNCTION="~nCSO~" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D4" FUNCTION="e_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C1" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C2" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D1" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D2" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H6" FUNCTION="r_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E1" FUNCTION="r_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E2" FUNCTION="r_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F1" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F2" FUNCTION="m_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H3" FUNCTION="m_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G1" FUNCTION="r_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G2" FUNCTION="t_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J6" FUNCTION="t_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J5" FUNCTION="m_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H1" FUNCTION="m_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H2" FUNCTION="m_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J3" FUNCTION="t_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J4" FUNCTION="t_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J1" FUNCTION="m_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J2" FUNCTION="m_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K5" FUNCTION="TDI" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="K2" FUNCTION="TCK" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="K6" FUNCTION="TMS" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="L5" FUNCTION="TDO" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="L6" FUNCTION="DCLK" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="K4" FUNCTION="DATA0" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="K1" FUNCTION="nCE" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="L1" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L2" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L4" FUNCTION="nCONFIG" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="M1" FUNCTION="clk" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M2" FUNCTION="reset" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M5" FUNCTION="t_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M6" FUNCTION="res_out8" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N1" FUNCTION="res_out7" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N2" FUNCTION="nprime0_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P1" FUNCTION="res_out9" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P2" FUNCTION="t_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N6" FUNCTION="res_out12" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N5" FUNCTION="res_out3" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N4" FUNCTION="res_out10" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P3" FUNCTION="nprime0_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P5" FUNCTION="r_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P6" FUNCTION="res_out15" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R1" FUNCTION="res_out0" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R2" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T1" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T2" FUNCTION="nprime0_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P4" FUNCTION="r_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R4" FUNCTION="n_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U1" FUNCTION="res_out5" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U2" FUNCTION="res_out6" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R5" FUNCTION="n_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R6" FUNCTION="n_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V1" FUNCTION="n_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V2" FUNCTION="res_out4" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T5" FUNCTION="res_out13" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T6" FUNCTION="res_out14" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T3" FUNCTION="n_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U3" FUNCTION="n_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W1" FUNCTION="res_out2" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W2" FUNCTION="res_out1" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y1" FUNCTION="res_out11" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y2" FUNCTION="n_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W3" FUNCTION="n_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W4" FUNCTION="n_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y3" FUNCTION="n_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y4" FUNCTION="n_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W5" FUNCTION="n_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U4" FUNCTION="n_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V4" FUNCTION="n_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y5" FUNCTION="n_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA5" FUNCTION="n_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V8" FUNCTION="m_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W7" FUNCTION="m_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V9" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y9" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W9" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U9" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U10" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB8" FUNCTION="nprime0_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA8" FUNCTION="m_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y10" FUNCTION="nprime0_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB9" FUNCTION="nprime0_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA9" FUNCTION="nprime0_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W11" FUNCTION="t_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V11" FUNCTION="t_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB10" FUNCTION="t_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA10" FUNCTION="t_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB11" FUNCTION="t_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA11" FUNCTION="m_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U11" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB12" FUNCTION="t_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA12" FUNCTION="t_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB13" FUNCTION="m_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA13" FUNCTION="t_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U13" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y13" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y17" FUNCTION="exp_state4" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AB20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="AA20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W20" FUNCTION="~LVDS142p/nCEO~" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W18" FUNCTION="exp_state3" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U18" FUNCTION="exp_state1" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="W22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="Y22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="V22" FUNCTION="exp_state0" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="U22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="T22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="R20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="P22" FUNCTION="state0" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N20" FUNCTION="nSTATUS" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="N18" FUNCTION="CONF_DONE" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="N17" FUNCTION="MSEL1" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="M17" FUNCTION="MSEL0" SIGNAL="DIG" IO="IN" CONTROL="CNTL" POLARITY="P"/>
<PIN PIN_NUM="N21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="N22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M19" FUNCTION="t_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M21" FUNCTION="m_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="M22" FUNCTION="m_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L21" FUNCTION="startCompute" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L22" FUNCTION="startInput" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L19" FUNCTION="r_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K22" FUNCTION="state1" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J21" FUNCTION="nprime0_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="L17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K17" FUNCTION="r_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K18" FUNCTION="state2" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="K20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="J17" FUNCTION="r_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F21" FUNCTION="r_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="H17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G17" FUNCTION="r_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C21" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C22" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D19" FUNCTION="r_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A20" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A19" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A18" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D16" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E15" FUNCTION="state3" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D15" FUNCTION="r_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C14" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A17" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E14" FUNCTION="exp_state2" SIGNAL="DIG" IO="OUT" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D14" FUNCTION="e_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F14" FUNCTION="e_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F13" FUNCTION="getResult" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B16" FUNCTION="e_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A16" FUNCTION="e_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B15" FUNCTION="r_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A15" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C13" FUNCTION="e_buf13" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F12" FUNCTION="r_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B14" FUNCTION="nprime0_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A14" FUNCTION="e_buf12" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B13" FUNCTION="nprime0_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A13" FUNCTION="t_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E12" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B11" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A11" FUNCTION="e_buf14" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E11" FUNCTION="e_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D11" FUNCTION="nprime0_buf1" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B10" FUNCTION="m_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A10" FUNCTION="nprime0_buf2" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F11" FUNCTION="nprime0_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F10" FUNCTION="e_buf15" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C10" FUNCTION="nprime0_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B9" FUNCTION="nprime0_buf3" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A9" FUNCTION="nprime0_buf4" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E9" FUNCTION="e_buf10" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D9" FUNCTION="e_buf11" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B7" FUNCTION="e_buf6" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F9" FUNCTION="e_buf9" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E8" FUNCTION="m_buf0" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D8" FUNCTION="e_buf8" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C9" FUNCTION="e_buf5" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="D7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E7" FUNCTION="r_buf7" SIGNAL="DIG" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="C7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A5" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A4" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="A3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="B3" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="F7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="E6" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G7" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>
<PIN PIN_NUM="G8" FUNCTION="" SIGNAL="NC" IO="IN" CONTROL="DATA" POLARITY="P"/>